---
fixes:
  - |
    Fixes a bug where Octavia configuration couldn't be generated for Antelope
    release while running Zed release kolla toolbox.
    `LP#2049364 <https://launchpad.net/bugs/2049364>`__
